### ISSUE TITLE
Review About text

### ISSUE THREAD

**Issue by jgagne** [PetraZelezna/english-for-designers#1]
- [x] Please review and revise your opening sentence. I get it, but it could be more clearly written. As a minimalist designer, the importance of details are a given, so "but that doesn’t mean I overlook the finest details" seems awkward and confusing. Try another approach in saying what you mean.
- [x] Also, your inclusion of the minimalist description seems a bit ironic and counter to the principle. Consider a minimalistic revision.
  - For example: Less decoration is more. Clarity and accessibility stand out from the crowd. …, etc.

I’ve added comments with a <del>line-through</del> for deletion and <b>bold</b> for inclusion for your consideration, if you don't choose a less minimalistic approach. 😉

- - -

I like to think of myself as a minimalist designer, but that doesn’t mean I overlook the finest details, which are important for a great design.

I'm known to be obsessed with my two beloved horses, but I also really like photography, pumpkin-spice lattes, and lazy days when I can finally have time to read books while listening to my favorite music or TV shows.

(Minimalist<del> description</del>: Great design doesn't necessarily <del>have</del> <b>need</b> to include countless <del>little</del> illustrations <b>or decorations</b> in a comprehensive and detailed graphic. It stands out from the crowd because it solves <del>the</del> <b>a</b> problem<del>. It is</del> <b>that  is</b> easily <del>understandable</del> <b>understood</b> by the audience <del>that feels</del> <b>and communicates</b> precisely what <del>the designer wants it to feel</del> <b>it was designed to communicate</b>. When it comes to minimalism, I try to capture the core message by using as <del>little</del> <b>few</b> distractive elements as possible and still delivering <del>a</del> <b>an effective and</b> great-looking design.)

**Comment by PetraZelezna** [comment]
I editted the text so that it would sound more natural.
