### ISSUE TITLE
CV about text feedback

### ISSUE THREAD

**Issue by jgagne** [PetraZelezna/english-for-designers#2]
# Petra Železná

## Product photographer and graphic designer

I was born in Czech Republic and have been always occupied by art and creative thoughts. Even though my designer path started in my mid teens, till then I have been interested in painting, drawing, creative writing. I have spent my childhood with camera and I still enjoy time shooting, especially product photography. In my free time you may find me reading or at the barn where I spend most of my free time taking care of horses and also giving lessons. My design style is meant to be clear, informative but also eye catching and esthetically pleasing.

- - -

- [x] Consider treating "Product photographer and graphic designer" as a heading and use title case to emphasis the distinct roles. If not, it could become and read more as a sentence, with the importance of a heading.
- [x] Consider changing the order of importance of sentences to better tell your story.
- [ ] Consider use of more active and confident language: "My design style is meant to be clear" to "My design style is clear".
- [x] Consider "until" in place of "till", "a camera" in place of "camera", etc. Check spelling and use of articles. 
- [x] Consider only using one instance of "free time" in use commas for listing those activities.
- [x] Consider removing words when and where possible that when removed, they aren't missed. For example: "I still enjoy time shooting, especially product photography", remove "time" to become "I still enjoy shooting, especially product photography".
- [x] Consider hyphenation of "eye-catching" and "mid-teens".

Edits:

# Petra Železná

## Product Photographer and Graphic Designer

or

## Czech-based product photographer and graphic designer.

My design style is clear, informative but also eye-catching and esthetically pleasing. I've always been captivated by art and creative thoughts. I spent my childhood with a camera and I still enjoy shooting, especially product photography. Even though my path as a designer started in my mid-teens, until then I have been interested in painting, drawing, creative writing. In my free time you may find me reading, or in the barn where I spend most of my time taking care of horses, and also giving lessons.

**Comment by PetraZelezna** [comment]
I have editted the misspelings, errors and deleted the words that I overused. But I kept the sentence order because I feel like they are ment to be in this order to make sense (in the beginnig paragraph). I think it did help the text. Thank you.
